In [ ]:
import numpy as np

# **Theoretical Question1**

 **Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**



Answer:

Purpose and Advantages of NumPy in Scientific Computing and Data Analysis
NumPy is a powerful library in Python for numerical and scientific computing. It is designed for handling large, multi-dimensional arrays and matrices of numerical data, and provides a wide range of mathematical functions to operate on these arrays. Here's how it enhances Python’s capabilities:

Efficient Array Handling: NumPy arrays are more efficient in terms of both time and memory compared to Python lists, especially when working with large datasets.

Vectorization: It allows for performing operations on entire arrays without needing explicit loops, which speeds up computations.

Mathematical Functions: NumPy provides a vast collection of mathematical functions like sin(), log(), and exp() that can be applied element-wise on arrays.

Integration with Other Libraries: NumPy is the foundation of many other libraries like Pandas, SciPy, and Scikit-learn, making it an essential tool for data analysis and machine learning.

# **Theoretical Question2**

Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Answer 2

Difference Between np.mean() and np.average()
np.mean(): Computes the arithmetic mean along the specified axis of the array. It is a simple, direct computation of the mean value.

np.average(): Computes the weighted average if weights are provided. Without weights, it behaves like np.mean(). It's more flexible than np.mean() because you can specify the weights for each element in the array.

When to Use:

Use np.mean() when you simply need the mean value.
Use np.average() when you need a weighted average.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))        # Output: 3.0
print(np.average(arr))     # Output: 3.0 (same as mean)

weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
print(np.average(arr, weights=weights))  # Weighted average


3.0
3.0
3.2


# **Theoretical Question3**

 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [ ]:
#1D Array: You can reverse the array using slicing [::-1].
arr = np.array([1, 2, 3, 4])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [4 3 2 1]


[4 3 2 1]


In [ ]:
#2D Array: Use slicing along specific axes to reverse rows or columns.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Reverse rows
reversed_rows = arr_2d[::-1]
print(reversed_rows)
# Reverse columns
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


# **Theoretical Question4**

How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.



In [ ]:
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64

arr_float = np.array([1.5, 2.5, 3.5])
print(arr_float.dtype)  # Output: float64


int64
float64


Importance of Data Types:

Memory Management: Choosing the correct data type helps in managing memory effectively, especially when dealing with large datasets.

Performance: Operations on arrays with smaller or more efficient data types (like float32 vs. float64) are faster.

# **Theoretical Question5**

Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray (N-dimensional array) is the core data structure in NumPy. Key features include:

Homogeneous: All elements in an ndarray must be of the same data type.
Multidimensional: Can have multiple dimensions (1D, 2D, 3D, etc.).
Efficient: Memory layout is contiguous, which allows fast access and manipulation.
Differences with Python Lists:

NumPy arrays are more memory efficient than Python lists and support vectorized operations, which makes them faster.
Python lists can store elements of different data types, while NumPy arrays are restricted to a single data type.

# **Theoretical Question6**

Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Memory Efficiency: NumPy arrays are stored in contiguous blocks of memory, unlike Python lists which are arrays of pointers to objects. This allows NumPy arrays to be more memory-efficient.

Speed: NumPy operations are implemented in C and optimized for performance, while Python lists are slower due to Python’s dynamic nature.

Vectorization: NumPy enables vectorized operations, meaning you can perform element-wise operations on entire arrays without explicit loops, which is much faster.

# **Theoretical Question7**

Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [ ]:
#np.vstack(): Stacks arrays vertically (row-wise). The number of columns must be the same for all arrays.
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.vstack((arr1, arr2))
print(result)


[[1 2]
 [3 4]]


In [ ]:
#np.hstack(): Stacks arrays horizontally (column-wise). The number of rows must be the same.
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4]


# **Theoretical Question8**

Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [ ]:
#np.fliplr(): Flips an array left to right (mirrors columns).

arr = np.array([[1, 2], [3, 4]])
print(np.fliplr(arr))

[[2 1]
 [4 3]]


In [ ]:
#np.flipud(): Flips an array upside down (mirrors rows).
arr = np.array([[1, 2], [3, 4]])
print(np.flipud(arr))

[[3 4]
 [1 2]]


# **Theoretical Question9**

Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
#The array_split() method splits an array into multiple sub-arrays. It can handle uneven splits, unlike split(), which requires the number of splits to divide evenly.

arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]


# **Theoretical Question10**

Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [ ]:
'''Vectorization: Refers to the ability to apply operations to entire arrays without needing to write explicit loops, which results in faster execution and cleaner code.

Broadcasting: NumPy automatically expands the dimensions of smaller arrays to match larger arrays during operations. This allows element-wise operations even when arrays of different shapes are involved.'''

arr1 = np.array([1, 2, 3])
arr2 = np.array([10])
result = arr1 + arr2  # Broadcasting arr2 to match arr1's shape
print(result)

[11 12 13]


# **Practical Questions1**

 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:\n", arr)
transposed_arr = arr.T  # Interchanging rows and columns
print("Transposed array:\n", transposed_arr)


Original array:
 [[17 34 43]
 [65 78 23]
 [17 48 46]]
Transposed array:
 [[17 65 17]
 [34 78 48]
 [43 23 46]]


# **Practical Questions2**

 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
arr = np.arange(10)
reshaped_2x5 = arr.reshape(2, 5)
reshaped_5x2 = arr.reshape(5, 2)
print("Reshaped 2x5 array:\n", reshaped_2x5)
print("Reshaped 5x2 array:\n", reshaped_5x2)


Reshaped 2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# **Practical Questions3**

Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
arr = np.random.random((4, 4))
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Array with border:\n", bordered_arr)


Array with border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.44640935 0.4734564  0.3177662  0.73628427 0.        ]
 [0.         0.09613937 0.65169095 0.94415223 0.91519757 0.        ]
 [0.         0.35440206 0.78616534 0.34769236 0.71176761 0.        ]
 [0.         0.48376618 0.31003519 0.98383531 0.01467485 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# **Practical Questions4**

Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
arr = np.arange(10, 61, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


# **Practical Questions5**

Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations.

In [ ]:
arr = np.array(['python', 'numpy', 'pandas'])
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


# **Practical Questions6**

Generate a NumPy array of words. Insert a space between each character of every word in the array

In [ ]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', list(words))

print("Words with spaces:", spaced_words)


Words with spaces: ['h e l l o' 'w o r l d' 'n u m p y']


# Practical **Questions7**

Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


# **Practical Questions8**

Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements



In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


# **Practical Questions9**

Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [ ]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
primes = arr[np.vectorize(is_prime)(arr)]

print("Prime Numbers:", primes)


Prime Numbers: [617 173 373  73   7 211 727  67 619 503 491 823 859 317 421 887  17  17
 547]


# **Practical Questions10**

Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
import numpy as np

# Generate a NumPy array of 30 random integers for daily temperatures
temperatures = np.random.randint(20, 35, 30)

# Reshape into 5 weeks (rows), 6 days each (columns)
weekly_temperatures = temperatures.reshape(5, 6)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Weekly Average Temperatures:", weekly_averages)


Weekly Average Temperatures: [25.66666667 25.16666667 25.83333333 25.33333333 23.83333333]
